# Generated by Django 4.1.7 on 2026-02-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='octofituser',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
